name: Handle Documentation Improvement Issues

on:
  issues:
    types: [opened]

jobs:
  tag-and-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Check user contribution preference
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        
        run: |
          # Define the messages and labels based on the user's choice
          if [[ "$ISSUE_BODY" == *"Yes, I would like to contribute this change"* ]]; then
            gh issue comment $ISSUE_NUMBER --body "Thank you for volunteering to contribute! Please refer to our [Contributor's Guide](docs/CONTRIBUTOR.md) if you need help to get started. If you have any questions, feel free to contact us!"
          elif [[ "$ISSUE_BODY" == *"Yes, But Iâ€™m not sure how to make the changes"* ]]; then
            gh issue comment $ISSUE_NUMBER --body "Thanks for your interest in contributing! It looks like you'd like some help to get started. Please refer to our [Contributor's Guide](https://github.com/INFOM126-Automated-Software-Engineering/2048-groupe-02/blob/main/docs/CONTRIBUTOR.md) for more information, and feel free to ask questions!"
            gh issue edit $ISSUE_NUMBER --add-label "Help requested"
          elif [[ "$ISSUE_BODY" == *"No, I just want to suggest the improvement"* ]]; then
            echo "No action needed as the user does not want to contribute."
          else
            echo "No recognized response in issue body."
          fi
